### ISSUE TITLE
LCDproc is now officially on github

### ISSUE THREAD

**Issue by dglaude** [sylvandb/LCDproc#1]
Dear developper,

[LCDproc is officially migrating to github](https://github.com/lcdproc/lcdproc)

Quick check show that your copy is just an import from cvs and does not contain any new driver or bug fix we should adopt.

Maybe you want to delete this repository or make it a fork from the original.

Thanks

**Comment by sylvandb** [comment]
deleted all files from my master HEAD and added a README.md pointing to the official repo.

(I don't think it is possible to make it a fork with different commit ids in the history.)

Thanks for letting me know, and thanks for LCDproc!
